# -*- coding: utf-8 -*-
"""MA_TMILL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sphpn_37ULQEbXDlBhDPZ04j4tJe1c6L
"""

import streamlit as st
import pandas as pd
import os
import tempfile
from PyPDF2 import PdfMerger
from io import BytesIO
import zipfile

# -------------------- APP CONFIG --------------------
st.set_page_config(page_title="PDF Merger", layout="wide")
st.title("📄 Invoice / SES Copy / RR Merger")

# -------------------- UTILITY FUNCTIONS --------------------
def clean_str(value):
    if pd.isna(value):
        return ""
    value = str(value).strip()
    if value.endswith(".0"):
        value = value[:-2]
    return value

def save_uploaded_files(uploaded_files, target_dir):
    for file in uploaded_files:
        with open(os.path.join(target_dir, file.name), "wb") as f:
            f.write(file.getbuffer())

def find_invoice_pdf(folder, memo_no, bill_no):
    """
    Try MEMO NO first, then BILL NO
    """
    for file in os.listdir(folder):
        if file.lower().endswith(".pdf"):
            if memo_no and memo_no in file:
                return os.path.join(folder, file)
            if bill_no and bill_no in file:
                return os.path.join(folder, file)
    return None

def find_pdf(folder, keyword):
    if not keyword:
        return None
    for file in os.listdir(folder):
        if keyword in file and file.lower().endswith(".pdf"):
            return os.path.join(folder, file)
    return None

# -------------------- TEMP WORKSPACE (SESSION ONLY) --------------------
BASE_DIR = tempfile.mkdtemp()

INVOICES_DIR = os.path.join(BASE_DIR, "INVOICES")
SES_DIR = os.path.join(BASE_DIR, "SES_COPIES")
RR_DIR = os.path.join(BASE_DIR, "RR")
OUTPUT_DIR = os.path.join(BASE_DIR, "MERGED_PDFS")

for d in [INVOICES_DIR, SES_DIR, RR_DIR, OUTPUT_DIR]:
    os.makedirs(d, exist_ok=True)

# -------------------- FILE UPLOAD SECTION --------------------
st.header("1️⃣ Upload PDF Files")

c1, c2, c3 = st.columns(3)

with c1:
    invoices = st.file_uploader(
        "Upload INVOICE PDFs",
        type="pdf",
        accept_multiple_files=True
    )

with c2:
    ses_files = st.file_uploader(
        "Upload GENERATED BILL PDFs",
        type="pdf",
        accept_multiple_files=True
    )

with c3:
    rr_files = st.file_uploader(
        "Upload RR PDFs (optional)",
        type="pdf",
        accept_multiple_files=True
    )

if invoices:
    save_uploaded_files(invoices, INVOICES_DIR)

if ses_files:
    save_uploaded_files(ses_files, SES_DIR)

if rr_files:
    save_uploaded_files(rr_files, RR_DIR)

# -------------------- TABLE INPUT --------------------
st.header("2️⃣ Paste Details")

columns = [
    "MEMO NO",
    "BILL NO",
    "E-INVOICE NO",
    "RR",
    "RENAME"
]

input_df = st.data_editor(
    pd.DataFrame(columns=columns),
    num_rows="dynamic",
    use_container_width=True
)

# -------------------- PROCESS & DOWNLOAD --------------------
st.header("3️⃣ Merge & Download")

if st.button("🚀 Merge PDFs"):
    if input_df.empty:
        st.error("Please enter at least one row.")
        st.stop()

    logs = []

    for idx, row in input_df.iterrows():
        try:
            memo_no = clean_str(row["MEMO NO"])
            bill_no = clean_str(row["BILL NO"])
            einv_no = clean_str(row["E-INVOICE NO"])
            rr_no = clean_str(row["RR"])
            rename = clean_str(row["RENAME"])

            if not (memo_no or bill_no):
                logs.append(f"Row {idx}: ❌ Missing Memo & Bill No")
                continue

            if not einv_no or not rename:
                logs.append(f"Row {idx}: ❌ Missing E-Invoice or Rename value")
                continue

            invoice_pdf = find_invoice_pdf(INVOICES_DIR, memo_no, bill_no)
            einv_pdf = find_pdf(SES_DIR, einv_no)
            rr_pdf = find_pdf(RR_DIR, rr_no) if rr_no else None

            if not invoice_pdf:
                logs.append(f"Row {idx}: ❌ Invoice PDF not found")
                continue

            if not einv_pdf:
                logs.append(f"Row {idx}: ❌ E-Invoice PDF not found")
                continue

            merger = PdfMerger()
            merger.append(invoice_pdf)
            merger.append(einv_pdf)

            if rr_pdf:
                merger.append(rr_pdf)

            output_path = os.path.join(OUTPUT_DIR, f"{rename}.pdf")
            merger.write(output_path)
            merger.close()

            logs.append(f"Row {idx}: ✅ Created {rename}.pdf")

        except Exception as e:
            logs.append(f"Row {idx}: ❌ Error → {e}")

    # -------------------- ZIP OUTPUT --------------------
    zip_buffer = BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zipf:
        for file in os.listdir(OUTPUT_DIR):
            zipf.write(
                os.path.join(OUTPUT_DIR, file),
                arcname=file
            )

    st.success("Processing completed.")

    st.download_button(
        label="⬇️ Download Merged PDFs (ZIP)",
        data=zip_buffer.getvalue(),
        file_name="merged_pdfs.zip",
        mime="application/zip"
    )

    with st.expander("📋 Processing Log"):
        for l in logs:
            st.write(l)
